require:
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - gemfiles/*
    - spec/dummy/**/*
    - lib/generators/lets_encrypt/templates/*
    - vendor/**/*

Rails:
  Enabled: true

Naming/FileName:
  Exclude:
    - lib/rails-letsencrypt.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
